#!/usr/bin/env bash
# Sync hfb sources into the self-contained Hugging Face Space folder.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DST="$ROOT/space/hopf-flux-bubble"

mkdir -p "$DST"
rm -rf "$DST/hfb"

COMMIT="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo local)"
UPDATED="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "$ROOT/web/build_info.py" <<EOF
"""Auto-generated by scripts/sync_hf_space.sh — do not edit by hand."""

BUILD_COMMIT = "$COMMIT"
BUILD_UPDATED_UTC = "$UPDATED"
EOF

cp -r "$ROOT/hfb" "$DST/"
cp -r "$ROOT/configs" "$DST/"
cp "$ROOT/web/demo_core.py" "$DST/"
cp "$ROOT/web/build_info.py" "$DST/"
cp "$ROOT/web/gradio_demo.py" "$DST/app.py"

cat > "$DST/requirements.txt" <<'EOF'
# Shared core — Hopf maps, defects, grids (canonical)
flux-hopf-lib==0.2.1

numpy>=1.24.0,<3.0.0
scipy>=1.10.0
matplotlib>=3.7.0
pyyaml>=6.0
pydantic==2.10.6
sympy>=1.12
EOF

{
  cat <<'EOF'
---
title: Hopf Flux Bubble
emoji: 🫧
colorFrom: green
colorTo: blue
sdk: gradio
sdk_version: 5.12.0
python_version: 3.12
app_file: app.py
pinned: false
license: mit
short_description: Analog flux bubble metrics — browser demo
---

EOF
  cat "$ROOT/docs/HF_SPACE_README.md"
} > "$DST/README.md"

echo "Synced → $DST"
ls -la "$DST"